name: Add New Dataset
description: Provide necessary information and create the required components for adding a new dataset.
title: "Add Dataset: [Dataset Name]"
labels: ["new dataset", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Please follow the template when proposing and working on a new dataset contribution.**
  - type: textarea
    id: description
    attributes:
      label: Dataset Description
      description: Describe the dataset comprehensively
      placeholder: |
        * Origin (source, links):
        * Academic Paper (title, links):
        * Content (type of data):
        * Size (approximate):
        * Licensing:
    validations:
      required: true
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Download/Extraction Script
        - label: Dataset Test
        - label: Tutorial
        - label: cli support
  - type: textarea
    id: considerations
    attributes:
      label: Additional Considerations
      description: |
        Please address:
        * Versioning: How will you handle dataset updates?
        * Documentation:  How will you document the dataset?
  - type: dropdown
    id: license
    attributes:
      label: license
      description: Does the license permit inclusion in this repository?
      options:
        - "yes"
        - "no"
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      options:
        - label: I have read the contribution guidelines.
        - label: I have provided a thorough dataset description.
        - label: My scripts and tests work as intended.
        - label: The tutorial demonstrates dataset usage clearly.
