{% set version = "0.1.0" %}

package:
  name: fintorch
  version: {{ version }}


build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fintorch

about:
  home: https://github.com/AI4FinTech/FinTorch
  license: MIT
  summary: 'AI4Fintech fintorch repository'
  description: |
    Code related to the AI4FinTech project
  dev_url: https://github.com/AI4FinTech/FinTorch
  doc_url: https://fintorch.readthedocs.io/
  doc_source_url: https://github.com/AI4FinTech/FinTorch/blob/master/README.rst
