name: Python Package testing using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: >-
          python3 -m
          pip install -r requirements_dev.txt
      - name: Build a binary wheel and a source tarball
        run: python3 -m pytest tests/
